{% set name = "conspire" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/conspire-{{ version }}.tar.gz
  sha256: d4cdbd93f010c29c99f3c02ffe7a519cb217426df375290fff1183fc85fc7706

build:
  number: 0
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - maturin
    - pip
    - python
  run:
    - numpy
    - python

test:
  commands:
    - pip check
    - pytest
  imports:
    - conspire
  requires:
    - pip
    - pytest
  source_files:
    - pyproject.toml
    - tests/

about:
  home: https://mrbuche.github.io/conspire
  description: c o n s p i r e
  dev_url: https://github.com/mrbuche/conspire
  license: GPL-2.0-or-later
  license_file:
    - THIRDPARTY.yml
    - LICENSE
  summary: c o n s p i r e

extra:
  recipe-maintainers:
    - mrbuche
